apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-news
commonLabels:
  app: kube-news
secretGenerator:
  - name: kube-news-secret
    literals:
      - DB_DATABASE=kube-news
      - DB_USERNAME=luiz
      - DB_PASSWORD=Teste123*
      - DB_HOST=postgres-service
  - name: postgres-secret
    literals:
      - POSTGRES_DB=kube-news
      - POSTGRES_USER=luiz
      - POSTGRES_PASSWORD=Teste123*
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
